import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { MoralisProvider } from 'react-moralis'
import Header from "../components/Header"
import Head from 'next/head'


const MORALIS_SERVER_URL = process.env.NEXT_PUBLIC_MORALIS_SERVER_URL
const APP_ID = process.env.NEXT_PUBLIC_MORALIS_APP_ID

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <MoralisProvider serverUrl={MORALIS_SERVER_URL} appId={APP_ID}> 
        <Header />
        <Component {...pageProps} />
      </MoralisProvider>
    </>
  )
}

export default MyApp
